
services:



  db:
    container_name: postgres_db
    image: postgres:latest

    ports:
      - "5432:${PORT}"

    environment:
      POSTGRES_URL: jdbc:postgresql://localhost:${PORT}/${DATABASE}
      POSTGRES_USER: ${USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}

    volumes:
      - postgres:/var/lib/postgresql/data

    networks:
      - catalog-network

networks:
  catalog-network:
    driver: bridge
